Fixed issue that startCopyFromURL and copyFromURL API not respect `--disableProductStyleUrl` parameter in parse source Uri
Azure/Azurite pull request #1252
Opened 2021-12-27 07:23 UTC by blueww

Thanks for contribution! Please go through following checklist before sending PR.

### PR Branch Destination

- For Azurite V3, please send PR to `main` branch.
- For legacy Azurite V2, please send PR to `legacy-dev` branch.

### Always Add Test Cases

Make sure test cases are added to cover the code change.

### Add Change Log

Add change log for the code change in `Upcoming Release` section in `ChangeLog.md`.

### Development Guideline

Please go to CONTRIBUTION.md for steps about setting up development environment and recommended Visual Studio Code extensions.

2022-01-06 12:13 UTC, wiruzman commented
Could you link the issue here?

2022-01-07 02:13 UTC, blueww commented
@wiruzman 
The issue is already linked.
See the [first comments in the PR](https://github.com/Azure/Azurite/pull/1252#issue-1089029457), it has : Fix issue #1245

2022-01-07 09:35 UTC, wiruzman commented
It just do not show up here:
![image](https://user-images.githubusercontent.com/7511734/148523851-a8d6ce63-c945-4ffc-918c-83b014c73202.png)

2022-01-07 09:37 UTC, wiruzman commented
Another question, do you know when this PR is going to be merged?

2022-01-07 09:44 UTC, blueww commented
@XiaoningLiu 
Would you please help to look at this PR?

2022-01-12 10:03 UTC, XiaoningLiu commented on src/blob/generated/Context.ts
> +  public get disableProductStyleUrl(): boolean | undefined {
Please add these 2 methods into `BlobContext` or "Queue|TableContext". All files under "generated" folder shouldn't be manually edited.

2022-01-12 10:04 UTC, XiaoningLiu requested changes
One comment added, others look good. Thanks for the update!

2022-01-13 06:01 UTC, blueww commented on src/blob/generated/Context.ts
> +  public get disableProductStyleUrl(): boolean | undefined {
fixed

2022-01-14 06:48 UTC, blueww commented
/azp run

2022-01-17 22:34 UTC, wiruzman commented
/azp run

2022-01-19 08:31 UTC, blueww commented
@XiaoningLiu 

I have fixed the comment from you, and the CI passed.
Would you please help to check if the PR is OK to you?

2022-01-21 04:27 UTC, XiaoningLiu approved these changes

2022-01-21 04:27 UTC, merged