Fix batch handling of empty partition key and empty row key
Azure/Azurite pull request #1364
Opened 2022-02-28 06:44 UTC by joelverhagen

Resolve https://github.com/Azure/Azurite/issues/1234.

2022-02-28 06:45 UTC, joelverhagen commented
@edwin-huber, I took a stab at https://github.com/Azure/Azurite/issues/1234. I saw you were assigned so I hope you haven't started working on it. If so, feel free to repurpose/toss out this PR 😃.

2022-03-01 07:37 UTC, edwin-huber commented on src/table/handlers/TableHandler.ts
> +    partitionKey: string | undefined,
@XiaoningLiu extending the parameter in the function signature with undefined is valid based on the "Duck Typing" in Typescript.
Are you happy with this?

2022-03-01 07:50 UTC, edwin-huber commented
Thanks for the submission!
I like the changes; I have one small suggestion and would like @XiaoningLiu to weigh in on the Handler Method signature.

2022-03-02 23:32 UTC, joelverhagen commented on src/table/handlers/TableHandler.ts
> +    partitionKey: string | undefined,
I think empty string is not a good indicator of missing value. An empty string is actually a valid partition key and `undefined` means the value should be picked from the context if possible.

2022-03-03 08:27 UTC, XiaoningLiu approved these changes

2022-03-10 08:50 UTC, XiaoningLiu commented
@edwin-huber Do you have other comments before merging this PR?

2022-03-10 12:01 UTC, edwin-huber requested changes
Please collect all checks for values into a single function.
This will help us when we update validation logic in the future.

```
partitionKey = partitionKey !== undefined ? partitionKey : tableContext.partitionKey!;
```

2022-03-10 18:47 UTC, joelverhagen commented on src/table/handlers/TableHandler.ts
> +    }
Done.

2022-03-10 18:58 UTC, edwin-huber approved these changes

2022-03-15 00:12 UTC, joelverhagen commented
Are there any other things I should address before the merge? Happy to fix whatever 😃

2022-03-16 09:07 UTC, merged