Add support for user delegation key
Azure/Azurite pull request #1753
Opened 2022-11-16 07:11 UTC by EmmaZhu

Thanks for contribution! Please go through following checklist before sending PR.

### PR Branch Destination

- For Azurite V3, please send PR to `main` branch.
- For legacy Azurite V2, please send PR to `legacy-dev` branch.

### Always Add Test Cases

Make sure test cases are added to cover the code change.

### Add Change Log

Add change log for the code change in `Upcoming Release` section in `ChangeLog.md`.

### Development Guideline

Please go to CONTRIBUTION.md for steps about setting up development environment and recommended Visual Studio Code extensions.

2022-11-25 03:35 UTC, XiaoningLiu commented on src/blob/generated/utils/utils.ts
> +export function getUserDelegationKeyValue(
Files under `generated` folder are supposed to be auto generated cross all services.
Should move the UDK utilities somewhere else.

2022-11-25 03:37 UTC, XiaoningLiu commented on src/blob/handlers/ServiceHandler.ts
> +      AAD_OBJECT_ID,
object id and tenant id should be extracted from incoming bearer token.

2022-11-25 03:47 UTC, XiaoningLiu requested changes
Added comments inline

2022-12-19 01:37 UTC, EmmaZhu commented on src/blob/generated/utils/utils.ts
> +export function getUserDelegationKeyValue(
Updated.

2022-12-19 01:37 UTC, EmmaZhu commented on src/blob/handlers/ServiceHandler.ts
> +      AAD_OBJECT_ID,
Updated.

2022-12-28 03:04 UTC, XiaoningLiu approved these changes

2022-12-28 14:12 UTC, blueww approved these changes

2023-01-06 02:08 UTC, merged