Fix subStringEnd calculation
Azure/Azurite pull request #1843
Opened 2023-03-17 16:45 UTC by haodeon

Fixes #1842

PR has test for change and updated changelog.

@microsoft-github-policy-service agree

2023-03-17 16:49 UTC, haodeon commented
@microsoft-github-policy-service agree

2023-03-21 09:26 UTC, edwin-huber commented on src/table/batch/TableBatchSerialization.ts
>            // remove 1 \r\n
The comment no longer matches what the code is doing.

2023-03-21 09:28 UTC, edwin-huber requested changes
Thanks for taking the time to figure this out and submit a change. 😸 
Please look at the changes requested.

2023-03-21 09:28 UTC, edwin-huber commented on tests/table/unit/deserialization.unit.test.ts
> +  it("deserializes, mock table batch request containing 4 deletes correctly", (done) => {
The test in this case is only checking the ```\n``` case, could you include a mock request using the Windows line endings as well?
Thanks!

2023-03-22 01:42 UTC, haodeon commented on src/table/batch/TableBatchSerialization.ts
>            // remove 1 \r\n
The comment was introduced in 95a932ec4403bc70faf86fd22ad75c00228a8762 which also changed `subStringEnd`.
I couldn't understand how the comment matched the code, so I avoided changing it.
The comment is now updated.

2023-03-22 01:58 UTC, haodeon commented on tests/table/unit/deserialization.unit.test.ts
> +  it("deserializes, mock table batch request containing 4 deletes correctly", (done) => {
I have added a mock request string and test case for `\r\n`.

While implementing the new test case, I found a potential bug in https://github.com/Azure/Azurite/blob/e5b5d588435f175e5bcb956f36ec677a294119ba/src/common/batch/BatchOperation.ts#L25

My test case was failing but only for the last operation in a batch. I eventually worked out the last ETag in the batchOperationArray has an extra `\r` but only when the batch uses `\r\n\` line endings.

I checked the behaviour of deserializeBatchRequest before this PR and it is the same, the last Etag has an extra `\r`.

In the new test, when asserting the Etag header for the last operation, the expected string has an extra `\r` at the end.

2023-03-22 21:56 UTC, haodeon commented on tests/table/unit/deserialization.unit.test.ts
> +  it("deserializes, mock table batch request containing 4 deletes correctly", (done) => {
I removed the extra `\r` from expected string in the new test. It is passing after rawHeaders has been fixed.

2023-05-10 03:18 UTC, haodeon commented
Hey @edwin-huber or @blueww,

Is there anything else required to merge this PR?

The issue here is affecting my team daily.

2023-05-10 03:28 UTC, blueww commented
/azp run

2023-05-10 05:23 UTC, blueww commented
@haodeon 
Would you please merge the latest Azurite change to the PR?
If the PR check can pass after merge the latest change, I will merge this PR.

2023-05-10 09:23 UTC, blueww commented on ChangeLog.md
> +- Fixed issue with headers length when deserializing batch deletes.
Please move the change log under the Upcoming release.
It's currently in 3.23.0 release, which is already published without this change.

2023-05-10 09:41 UTC, haodeon commented on ChangeLog.md
> +- Fixed issue with headers length when deserializing batch deletes.
I have made the requested change.

2023-05-11 00:37 UTC, haodeon commented
@blueww
Please let me know what you would like done about the one failing test.

2023-05-11 03:13 UTC, merged

2023-05-11 03:13 UTC, blueww commented
@haodeon 

Thanks for the contribution!
I have rerun the test and it passed, so merge the PR.