"Update, Delete and Merge entities throw InvalidInput error for Malformed Etag"
Azure/Azurite pull request #2062
Opened 2023-07-21 08:10 UTC by PrasantJillella

2023-07-21 08:36 UTC, blueww requested changes
Please see my comments to fix the build failure.
Please add change log: https://github.com/Azure/Azurite/blob/main/ChangeLog.md

2023-07-21 08:36 UTC, blueww commented on src/table/handlers/TableHandler.ts
> +        throw StorageErrorFactory.getInvalidInput(context, "Bad Request");
Build fail. It should be 
      `throw StorageErrorFactory.getInvalidInput(context);`
Same as below.

2023-07-21 08:43 UTC, PrasantJillella commented on src/table/handlers/TableHandler.ts
> +        throw StorageErrorFactory.getInvalidInput(context, "Bad Request");
removed additionalMessages parameter to prevent build failure.
please take a look and let me know if build succeeds now.
thank you.

2023-07-21 10:07 UTC, blueww commented
The test case build fail:

 

> tests/table/apis/table.entity.issues.test.ts(220,11): error TS1155: 'const' declarations must be initialized.
> tests/table/apis/table.entity.issues.test.ts(232,17): error TS2554: Expected 2-3 arguments, but got 1.
> tests/table/apis/table.entity.issues.test.ts(234,15): error TS2454: Variable 'rowKey' is used before being assigned.
> tests/table/apis/table.entity.issues.test.ts(244,15): error TS2454: Variable 'rowKey' is used before being assigned.
> tests/table/apis/table.entity.issues.test.ts(252,17): error TS2551: Property 'mergeEntity' does not exist on type 'TableClient'. Did you mean 'getEntity'?
> tests/table/apis/table.entity.issues.test.ts(254,15): error TS2454: Variable 'rowKey' is used before being assigned.
> tests/table/apis/table.entity.issues.test.ts(256,15): error TS7006: Parameter 'reason' implicitly has an 'any' type.

2023-07-21 10:08 UTC, blueww commented on tests/table/apis/table.entity.issues.test.ts
> +    const rowKey: "𐐷RK1"
should be "=" instead of ":"

2023-07-21 10:10 UTC, blueww commented on tests/table/apis/table.entity.issues.test.ts
> +    tableClient.deleteEntity({
How about update the delete test to :
```
    tableClient.deleteEntity(
      partitionKey,
      rowKey,
      {
        etag: malformedEtag
      }
    ).catch((reason) => {
      assert.strictEqual(reason.details.errorCode, "InvalidInput");
      assert.strictEqual(reason.statusCode, 400);
    });
```

2023-07-21 18:05 UTC, PrasantJillella commented on tests/table/apis/table.entity.issues.test.ts
> +    tableClient.deleteEntity({
sure

2023-07-21 18:40 UTC, PrasantJillella commented on tests/table/apis/table.entity.issues.test.ts
> +    const rowKey: "𐐷RK1"
sorry, copy paste error.

2023-07-21 18:40 UTC, PrasantJillella commented on tests/table/apis/table.entity.issues.test.ts
> +    const rowKey: "𐐷RK1"
updated.

2023-07-24 01:53 UTC, blueww commented on tests/table/apis/table.entity.issues.test.ts
> +    const rowKey: "𐐷RK1"
It looks still not updated in this PR.

2023-07-24 07:11 UTC, PrasantJillella reviewed
Addressing comments.

2023-08-04 06:42 UTC, blueww commented on tests/table/apis/table.entity.issues.test.ts
> +  it("Malformed Etag when sent as input throws InvalidInput for table operations, ", async() => {
Please add the new test case to the button of the file, below all existing test cases.

2023-08-04 21:59 UTC, PrasantJillella commented on tests/table/apis/table.entity.issues.test.ts
> +  it("Malformed Etag when sent as input throws InvalidInput for table operations, ", async() => {
sure, will update that.

2023-08-04 22:10 UTC, PrasantJillella commented on tests/table/apis/table.entity.issues.test.ts
> +  it("Malformed Etag when sent as input throws InvalidInput for table operations, ", async() => {
updated

2023-08-07 05:14 UTC, blueww approved these changes

2023-08-07 05:15 UTC, blueww requested changes
The code change looks good to me.
Would you please also add the change to changelog:  https://github.com/Azure/Azurite/blob/main/ChangeLog.md

2023-08-14 03:04 UTC, blueww commented
@PrasantJillella 

The change log looks good to me. But why not add it into same PR as the code change？
For better tracking the code change in the future, normally we should have change log in same PR with the code change.

2023-08-14 03:05 UTC, blueww commented
/azp run

2023-08-14 08:03 UTC, PrasantJillella commented
Hi Sorry, I didn't realize that they were both from same repository.
Updating the commit.

2023-08-16 08:49 UTC, blueww commented
@PrasantJillella 

Please note, there still 2 things blocked the PR from merge:
1. you still not agree the license/cla. 
2. the change log is not added to same PR with code change.

2023-08-18 07:27 UTC, PrasantJillella commented
@microsoft-github-policy-service agree company="Microsoft"

2023-08-18 07:27 UTC, PrasantJillella commented
> @PrasantJillella please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

2023-08-18 07:34 UTC, PrasantJillella commented
> @PrasantJillella
> 
> Please note, there still 2 things blocked the PR from merge:
> 
> 1. the license/cla is still not agreed by you.
> 2. the change log is not added to same PR with code change.

Updated. Please take a look.

2023-08-18 09:39 UTC, blueww commented on ChangeLog.md
> +
Add the change log to "## Upcoming Release" above.

2023-08-18 09:41 UTC, PrasantJillella commented on ChangeLog.md
> +
sure

2023-08-18 09:48 UTC, PrasantJillella commented on ChangeLog.md
> +
updated

2023-08-21 02:04 UTC, blueww approved these changes

2023-08-21 02:11 UTC, merged