Only include metadata when requested
Azure/Azurite pull request #2472
Opened 2024-10-04 16:02 UTC by frederikrosenberg

Closes #1730

Only include metadata when requested on blob list endpoints.

2024-10-04 16:03 UTC, frederikrosenberg commented
@microsoft-github-policy-service agree

2024-10-08 07:20 UTC, blueww commented on tests/blob/apis/container.test.ts
> +    const metadata = {
As 2 APIs are updated, the test should cover both 2 APIs.

2024-10-08 07:21 UTC, blueww requested changes
The change generally looks good to me. 
Only a comment for testing.

2024-10-09 02:29 UTC, blueww approved these changes

2024-10-09 07:37 UTC, merged