Check both Content-MD5 and x-ms-blob-content-md5
Azure/Azurite pull request #2487
Opened 2024-11-10 18:50 UTC by gaul

2024-11-11 02:49 UTC, blueww requested changes
Please add a test case to cover it.
Besides that, please consider that API which support Content-MD5 and x-ms-blob-content-md5.

2024-11-11 06:28 UTC, gaul commented
Could you expand on your suggestion?  I believe that for block blobs `Content-MD5` and `x-ms-blob-content-md5` are synonyms: https://technet2.github.io/Wiki/blogs/windowsazurestorage/windows-azure-blob-md5-overview.html .  It appears that the JavaScript API only sends the former but the Java API sends the latter.  How can I inject a header that is not have a `x-ms-meta-` prefix?

2025-01-13 01:50 UTC, gaul commented
@blueww Is there any way to move this PR forward?  I don't believe that the test you suggested is possible with the SDK.

2025-01-13 03:27 UTC, blueww commented
@gual

Please refer this test case for how to add header to request send from Storage JS SDK with customized policy.

https://github.com/Azure/Azurite/blob/3e25ee56cfdf3a0b236cedb781152b1073ec41d6/tests/table/auth/tableCorsRequest.test.ts#L64

The customized policy class is defined in https://github.com/Azure/Azurite/blob/main/tests/blob/RequestPolicy/OPTIONSRequestPolicyFactory.ts

The sample test case changes several items in the request, if only for header, see a more simple guild in https://github.com/Azure/Azurite/pull/2462#issuecomment-2340150113

2025-01-14 04:54 UTC, gaul commented
@blueww I added the suggested test -- please take a look.

2025-01-14 08:30 UTC, blueww commented on tests/blob/RequestPolicy/CustomMD5PolicyFactory.ts
> +    request.headers.set("x-ms-blob-content-md5", `${this.md5}`);
It would be better to write a more generic policy to add a header from input header name and value, then other coming test cases can also use it, instead of each header has seperate class to add header.

2025-01-15 03:05 UTC, blueww approved these changes

2025-01-15 06:48 UTC, merged